---
- name: for change soft link check
  file:
    src: "{{ use_project }}"
    dest: "{{ deploy_directory }}/{{ deploy_project_name }}"
    state: absent

- name: change soft link for process {{ project_name }}
  file:
    src: "{{ use_project }}"
    dest: "{{ deploy_directory }}/{{ deploy_project_name }}"
    state: link

- name: create static directory for {{ project_name }}
  file:
    path: "{{ mount_path }}"
    state: directory
    mode: 0755
  when: (hosts == "restapi") or (hosts == "teamshop")

  when: project_name == "rest-api" or project_name == "wxshop"
- name: check static upload directory
  file:
    path: "{{ mount_path }}/{{ mount_name }}"
    state: absent

- name: change static link for process {{ project_name }}
  file:
    src: "{{ project_static }}"
    dest: "{{ mount_path }}/{{ mount_name }}"
    state: link
  when: project_name != "api"


- name: include syzm_process main
  include: ejl_process/main.yml
